name: Tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Project checkout
        uses: actions/checkout@v1
      - name: Node.js setup
        uses: actions/setup-node@v1.1.0
      - name: installation of dependencies
        run: npm ci
      - name: E2E tests
        run: npm run pretest:github && npm test